alias bake='bundle exec rake'
alias be='bundle exec'
alias dbm='bundle exec rake db:migrate'
alias r='bundle exec rails'
alias rc='bundle exec rails c'
alias rg='bundle exec rails g'
alias rlog='tail -f log/development.log'
alias rn='bundle exec rails new'
alias rs='bundle exec rails s'
alias ru='bundle exec rackup'
alias rubobranch="git diff origin/master --name-only --diff-filter=AM | \grep .rb | \grep -v .rbi | xargs bin/rubocop -A --force-exclusion" # only run lint on files that changed in your branch
